import Accordion from "@/components/Accordion";
import Head from "next/head";

export default function Home({ categories }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="w-full bg-gray-200 flex flex-col justify-center items-center">
                <Accordion categories={categories} />
            </main>
        </>
    );
}

export async function getStaticProps() {
    const res = await fetch("https://mohsenfathipour.com/api/categories.json");
    const categories = await res.json();

    return {
        props: {
            categories,
        },
    };
}
